import type { User, Client, Task, Category, TaskType, CourierLocation, PerformanceMetrics, Branch } from '../types/index';

// Password for all demo users: "demo123"
export const mockUsers: User[] = [
    {
        id: 'u1',
        firstName: 'Admin',
        lastName: 'Principal',
        username: 'admin',
        email: 'admin@sgr.com',
        password: 'demo123',
        role: 'ADMIN',
        phone: '+57 300 1234567',
        active: true,
        branchId: 'b1',
        roleId: 'r1',
        createdAt: new Date('2024-01-01'),
        name: 'Admin Principal',
    },
    {
        id: 'u2',
        firstName: 'María',
        lastName: 'Rodríguez',
        username: 'maria',
        email: 'maria@sgr.com',
        password: 'demo123',
        role: 'ASESOR',
        phone: '+57 300 2345678',
        active: true,
        branchId: 'b1',
        roleId: 'r2',
        createdAt: new Date('2024-01-15'),
        name: 'María Rodríguez',
    },
    {
        id: 'u3',
        firstName: 'Carlos',
        lastName: 'Supervisor',
        username: 'carlos',
        email: 'carlos@sgr.com',
        password: 'demo123',
        role: 'SUPERVISOR',
        phone: '+57 300 3456789',
        active: true,
        branchId: 'b2',
        roleId: 'r3',
        createdAt: new Date('2024-02-01'),
        name: 'Carlos Supervisor',
    },
    {
        id: 'u4',
        firstName: 'Juan',
        lastName: 'Mensajero',
        username: 'juan',
        email: 'juan@sgr.com',
        password: 'demo123',
        role: 'MENSAJERO',
        phone: '+57 300 4567890',
        active: true,
        branchId: 'b1',
        roleId: 'r4',
        createdAt: new Date('2024-02-15'),
        name: 'Juan Mensajero',
    },
    {
        id: 'u5',
        firstName: 'Pedro',
        lastName: 'García',
        username: 'pedro',
        email: 'pedro@sgr.com',
        password: 'demo123',
        role: 'MENSAJERO',
        phone: '+57 300 5678901',
        active: true,
        branchId: 'b2',
        roleId: 'r4',
        createdAt: new Date('2024-03-01'),
        name: 'Pedro García',
    },
    {
        id: 'u6',
        firstName: 'Ana',
        lastName: 'Martínez',
        username: 'ana',
        email: 'ana@sgr.com',
        password: 'demo123',
        role: 'MENSAJERO',
        phone: '+57 300 6789012',
        active: true,
        branchId: 'b3',
        roleId: 'r4',
        createdAt: new Date('2024-03-15'),
        name: 'Ana Martínez',
    },
];

export const mockTaskTypes: TaskType[] = [
    {
        id: 'tt1',
        name: 'Entrega',
        code: 'entrega',
        description: 'Entrega de paquete o documento',
        active: true,
    },
    {
        id: 'tt2',
        name: 'Retiro',
        code: 'retiro',
        description: 'Retiro de paquete o documento',
        active: true,
    },
];

export const mockCategories: Category[] = [
    {
        id: 'c1',
        name: 'Equipos',
        description: 'Equipos electrónicos y tecnológicos',
        color: '#3b82f6',
        active: true,
    },
    {
        id: 'c2',
        name: 'Documentos',
        description: 'Documentos legales y administrativos',
        color: '#10b981',
        active: true,
    },
    {
        id: 'c3',
        name: 'Suministros',
        description: 'Suministros de oficina y materiales',
        color: '#f59e0b',
        active: true,
    },
    {
        id: 'c4',
        name: 'Medicamentos',
        description: 'Medicamentos y productos farmacéuticos',
        color: '#ef4444',
        active: true,
    },
    {
        id: 'c5',
        name: 'Alimentos',
        description: 'Alimentos y bebidas',
        color: '#8b5cf6',
        active: true,
    },
];

export const mockClients: Client[] = [
    {
        id: 'cl1',
        name: 'TechCorp Solutions',
        phone: '+57 601 2345678',
        rucCi: '80012345-9',
        address: 'Calle 72 #10-34',
        city: 'Bogotá',
    },
    {
        id: 'cl2',
        name: 'Farmacia Central',
        phone: '+57 601 3456789',
        rucCi: '80023456-7',
        address: 'Carrera 15 #85-20',
        city: 'Bogotá',
    },
    {
        id: 'cl3',
        name: 'Bufete Jurídico González',
        phone: '+57 601 4567890',
        rucCi: '80034567-5',
        address: 'Avenida 19 #120-45',
        city: 'Bogotá',
    },
    {
        id: 'cl4',
        name: 'Restaurante El Buen Sabor',
        phone: '+57 601 5678901',
        rucCi: '80045678-3',
        address: 'Calle 93 #13-22',
        city: 'Bogotá',
    },
    {
        id: 'cl5',
        name: 'Papelería Moderna',
        phone: '+57 601 6789012',
        rucCi: '80056789-1',
        address: 'Carrera 7 #32-16',
        city: 'Bogotá',
    },
];

export const mockBranches: Branch[] = [
    {
        id: 'b1',
        name: 'Sede Principal',
        address: 'Calle 100 #15-20',
        city: 'Bogotá',
        phone: '+57 601 1234567',
    },
    {
        id: 'b2',
        name: 'Sede Norte',
        address: 'Autopista Norte #140-10',
        city: 'Bogotá',
        phone: '+57 601 2345678',
    },
    {
        id: 'b3',
        name: 'Sede Occidente',
        address: 'Avenida Boyacá #26-30',
        city: 'Bogotá',
        phone: '+57 601 3456789',
    },
];

export const mockTasks: Task[] = [
    {
        id: 't1',
        title: 'Entrega de laptop Dell',
        description: 'Laptop Dell XPS 15 para el departamento de IT',
        status: 'in_progress',
        taskTypeId: 'tt1',
        categoryId: 'c1',
        clientId: 'cl1',
        assignedTo: 'u4',
        deliveryAddress: 'Calle 72 #10-34, Bogotá',
        deliveryLocation: { lat: 4.6533, lng: -74.0574 },
        priority: 'high',
        scheduledDate: new Date(),
        createdBy: 'u2',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 't2',
        title: 'Retiro de documentos legales',
        description: 'Contratos firmados para archivo',
        status: 'assigned',
        taskTypeId: 'tt2',
        categoryId: 'c2',
        clientId: 'cl3',
        assignedTo: 'u5',
        pickupAddress: 'Avenida 19 #120-45, Bogotá',
        deliveryAddress: 'Calle 26 #69-76, Bogotá',
        pickupLocation: { lat: 4.7110, lng: -74.0721 },
        deliveryLocation: { lat: 4.6482, lng: -74.1033 },
        priority: 'medium',
        scheduledDate: new Date(),
        createdBy: 'u2',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 't3',
        title: 'Entrega de medicamentos',
        description: 'Medicamentos de urgencia',
        status: 'pending',
        taskTypeId: 'tt1',
        categoryId: 'c4',
        clientId: 'cl2',
        deliveryAddress: 'Carrera 15 #85-20, Bogotá',
        deliveryLocation: { lat: 4.6690, lng: -74.0543 },
        priority: 'high',
        scheduledDate: new Date(),
        createdBy: 'u1',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 't4',
        title: 'Entrega de pedido de almuerzo',
        status: 'completed',
        taskTypeId: 'tt1',
        categoryId: 'c5',
        clientId: 'cl4',
        assignedTo: 'u6',
        deliveryAddress: 'Calle 93 #13-22, Bogotá',
        deliveryLocation: { lat: 4.6764, lng: -74.0538 },
        priority: 'medium',
        scheduledDate: new Date(Date.now() - 3600000),
        completedDate: new Date(Date.now() - 1800000),
        createdBy: 'u2',
        createdAt: new Date(Date.now() - 7200000),
        updatedAt: new Date(Date.now() - 1800000),
    },
    {
        id: 't5',
        title: 'Entrega de suministros de oficina',
        description: 'Papel, carpetas y material de oficina',
        status: 'in_progress',
        taskTypeId: 'tt1',
        categoryId: 'c3',
        clientId: 'cl5',
        assignedTo: 'u4',
        deliveryAddress: 'Carrera 7 #32-16, Bogotá',
        deliveryLocation: { lat: 4.6280, lng: -74.0673 },
        priority: 'low',
        scheduledDate: new Date(),
        createdBy: 'u2',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export const mockCourierLocations: CourierLocation[] = [
    {
        userId: 'u4',
        location: { lat: 4.6450, lng: -74.0650 },
        timestamp: new Date(),
        speed: 25,
        heading: 45,
    },
    {
        userId: 'u5',
        location: { lat: 4.6800, lng: -74.0800 },
        timestamp: new Date(),
        speed: 30,
        heading: 180,
    },
    {
        userId: 'u6',
        location: { lat: 4.6600, lng: -74.0700 },
        timestamp: new Date(),
        speed: 20,
        heading: 90,
    },
];

export const mockPerformanceMetrics: PerformanceMetrics[] = [
    {
        userId: 'u4',
        tasksCompleted: 45,
        tasksInProgress: 2,
        averageCompletionTime: 35,
        onTimeDeliveryRate: 94,
        customerRating: 4.7,
        totalDistance: 320,
    },
    {
        userId: 'u5',
        tasksCompleted: 38,
        tasksInProgress: 1,
        averageCompletionTime: 42,
        onTimeDeliveryRate: 89,
        customerRating: 4.5,
        totalDistance: 285,
    },
    {
        userId: 'u6',
        tasksCompleted: 52,
        tasksInProgress: 1,
        averageCompletionTime: 32,
        onTimeDeliveryRate: 96,
        customerRating: 4.9,
        totalDistance: 410,
    },
];
